### ISSUE TITLE
Cannot continue to play

### ISSUE THREAD

**Issue by themarkymark-steem** [holgern/steemmonsters#5]
I noticed recently it is only able to play a few games before it stops.

I far as I can see it finds a transaction, and then next line it says the same transaction cannot be found when trying to validate it.

**Comment by followbtcnews** [comment]
Yea I getting same errors

`followbtcnews rating: 4261, battles: 536, wins: 336, cur. streak: 0
sm_find_match broadcasted...
Transaction id found (27270711 - 892bbf26fe0b27894fca83dbc18a05c246327178)
Transaction [892bbf26fe0b27894fca83dbc18a05c246327178] not found.
sm> play water3
followbtcnews rating: 4261, battles: 536, wins: 336, cur. streak: 0
sm_find_match broadcasted...
Transaction id found (27270716 - 9ca3d7964af8d7876a78fef872193b5aa3fb07b4)
Transaction [9ca3d7964af8d7876a78fef872193b5aa3fb07b4] not found.
sm> Traceback (most recent call last):
`

**Comment by holgern** [comment]
Fixed in 0.0.14

**Comment by themarkymark-steem** [comment]
Looks like it is still happening.
